### ISSUE TITLE
Support both tag and digest

### ISSUE THREAD

**Issue by gnaponie** [konflux-ci/rpm-lockfile-prototype#15]
Hello.
Seems like skopeo does not support using both tag and digest: https://github.com/containers/image/issues/1736

This is an error we get when running the script:
```
skopeo --override-arch=amd64 copy docker://registry.access.redhat.com/ubi9/ubi:latest@sha256:66233eebd72bb5baa25190d4f55e1dc3fff3a9b77186c1f91a0abdb274452072 dir:/tmp/tmpz913lvuu
Invalid source name docker://registry.access.redhat.com/ubi9/ubi:latest@sha256:66233eebd72bb5baa25190d4f55e1dc3fff3a9b77186c1f91a0abdb274452072: Docker references with both a tag and digest are currently not supported
```

Seems like the script was tested only for image@tag.

Is there any plan to support that in some other way in the script? It seems like a lot of our users would like to specify tag and digest.
Thank you

**Comment by lubomir** [comment]
Is the desired behaviour to ensure that the digest matches the tag?

In that case it could be done by pulling the image by tag, and then checking if the digest matches.

**Comment by gnaponie** [comment]
The desired goal from us (renovate team) I believe it would be that the script doesn't throw an error. Otherwise we won't update the lockfile. Perhaps it could check if they match. If they don't it could just log a warning and "pick" one of the 2 (maybe the digest?)?
