### ISSUE TITLE
Resolving option in input file

### ISSUE THREAD

**Issue by jpopelka** [konflux-ci/rpm-lockfile-prototype#17]
Hi,

[I'm using](https://gitlab.com/redhat/rhel/containers/ubi10/-/blob/rhel-10.0-beta/rpms.in.yaml?ref_type=heads#L4) `--bare` for generating a lock file for a scratch/base image to resolve in an empty root.

For automation/Renovate it'd be nice to have the resolving option (Containerfile / image / local system / bare / rpm ostree treefile) specified in the input file so that the automation doesn't need to figure out which one to use.

**Comment by jpopelka** [comment]
Another use case is [rhel-bootc which uses `--rpm-ostree-treefile` ](https://gitlab.com/redhat/rhel/bifrost/rhel-bootc/-/blob/rhel-10.0-beta/README-lockfile.md?ref_type=heads#generating-the-lockfile) to generate the lock file.

**Comment by lubomir** [comment]
#20 contains a draft implementation for this. Please test and provide feedback on the pull request.
